config/routes.rb
Rails.application.routes.draw do
  resources :split_checks, only: %i[new create show] do
    get :demo, on: :collection
  end

  resources :components, only: :index

  namespace :components do
    resource :alert, only: :show do
      collection do
        get :result
      end
    end

    resource :barcode_scanner, only: :show

    resource :biometrics_lock, only: :show

    resource :button, only: :show do
      collection do
        get :text
        get :image
        get :left
        get :result
      end
    end

    resource :document_scanner, only: :show

    resource :form, only: %i[new create show]

    resource :haptic, only: :show

    resource :location, only: :show

    resource :menu, only: :show do
      collection do
        get :result
      end
    end

    resource :nfc, only: :show

    resource :notification_token, only: :show

    resource :permissions, only: :show

    resource :review_prompt, only: :show

    resources :searches, only: %i[index show]

    resource :share, only: :show do
      collection do
        get :current
        get :custom
      end
    end

    resource :theme, only: :show

    resource :toast, only: :show
  end

  # root "components#index"
  root 'split_checks#new'
end

app/views/shared/_flash.html.erb
<% if flash.notice.present? %>
  <div class="top-level-container margin-bs-l">
    <div class="alert alert--success" role="alert">
      <%= flash.notice %>
    </div>
  </div>
<% end %>

app/views/shared/_item.html.erb
<%= link_to path, data: local_assigns[:data] || {}, class: "list-group-item list-group-item-action d-flex py-3" do %>
  <div class="col flex-grow-0 flex-shrink-1 my-auto ps-1 pe-4">
    <i class="bi <%= icon %> fs-1"></i>
  </div>

  <div class="w-100 mx-auto">
    <p class="fs-5 d-flex align-items-middle mb-0">
      <% if local_assigns[:pro] %>
        <small><span class="badge bg-primary-subtle text-primary-emphasis me-2">PRO</span></small>
      <% end %>

      <span><%= name %></span>
    </p>
    <p class="mb-0 text-muted"><%= description %></p>
  </div>

  <div class="col flex-grow-0 flex-shrink-1 my-auto d-sm-none">
    <i class="bi bi-chevron-right"></i>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<header class="header top-level-container hide@native">
  <%= link_to root_path, class: "header__brand unstyled-link color-accent" do %>
    <%= sprite_tag "hotwire-native-logo", aria: { label: "Hotwire Native Demo" } %>
  <% end %>
  <nav>
    <ul class="main-navigation unstyled-list block-100">
      <li>
        <%= link_to "Navigation", root_path, class: "main-navigation__link decorated-link" %>
      </li>
      <li>
        <%= link_to " Bridge Components", components_path, class: "main-navigation__link decorated-link" %>
      </li>
      <li>
        <%= link_to "Resources", resources_path, class: "main-navigation__link decorated-link" %>
      </li>
    </ul>
  </nav>
</header>

app/views/shared/_pro_cta.html.erb
<div data-pro-cta class="alert alert-warning d-none" role="alert">
  <b>Warning</b>: This is a PRO component. It won't work correctly without a <a href="https://masilotti.com/bridge-components/pro" class="alert-link">PRO license</a>.
</div>

app/views/shared/_split_check_nav.html.erb
<header class="header top-level-container hide@native" data-controller="split-check-nav">
  <nav>
    <ul class="main-navigation unstyled-list block-100">
      <li>
        <%= link_to "Subir Nuevo Ticket", new_split_check_path, class: "main-navigation__link decorated-link", data: { action: "click->split-check-nav#clearSplitData" } %>
      </li>
      <li>
        <%= link_to "Components", components_path, class: "main-navigation__link decorated-link" %>
      </li>
      <li>
        <%= link_to "Demo", demo_split_checks_path, class: "main-navigation__link decorated-link" %>
      </li>
    </ul>
  </nav>
</header>